#!/bin/sh
set -e
export PATH="$HOME/.cargo/bin:$PATH"

echo '+cargo nextest run'
cargo nextest run --no-tests=pass
echo '+cargo clippy -- -D warnings'
cargo clippy -- -D warnings
echo '+cargo fmt -- --check'
cargo fmt -- --check
